#!/bin/bash -l
#PBS -N asra1_Asthma_Persons
#PBS -l ncpus=1
#PBS -l mem=2GB
#PBS -l walltime=0:20:00
#PBS -e QUTHPC_training/batch/outputs/lyra/20231109/lyra_errors/asra1_Asthma_Persons
#PBS -o QUTHPC_training/batch/outputs/lyra/20231109/lyra_out/asra1_Asthma_Persons

module load r/4.0.3-foss-2020b
module load gdal/3.2.1-foss-2020b

R -e ".libPaths('r_lib');
base_folder='QUTHPC_training/batch';
loop_output_file='QUTHPC_training/batch/outputs/Asthma/Persons/asra1_Asthma_Persons';
model_spec='asra1';
sex='Persons';
condition='Asthma';
cur_date='20231109';
niter=800;
nburnin=400;
thin=1;
nchains=4;
source('QUTHPC_training/batch/ms.R');"
