#!/bin/bash -l
#PBS -N asra2_Asthma_Male
#PBS -l ncpus=1
#PBS -l mem=2GB
#PBS -l walltime=1:00:00
#PBS -e QUTHPC_training/outputs/lyra/20230819/lyra_errors/asra2_Asthma_Male
#PBS -o QUTHPC_training/outputs/lyra/20230819/lyra_out/asra2_Asthma_Male

module load r/4.0.3-foss-2020b
module load gdal/3.2.1-foss-2020b

R -e ".libPaths('r_lib');
base_folder='QUTHPC_training';
loop_output_file='QUTHPC_training/outputs/Asthma/Male/asra2_Asthma_Male';
model_spec='asra2';
sex='Male';
condition='Asthma';
cur_date='20230819';
niter=800;
nburnin=400;
thin=1;
nchains=4;
source('QUTHPC_training/ms.R');"
